replicaCount: 2

image:
  repository: ghcr.io/fahriddin989/ci-cd-release-engineering-foundation
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPortName: http

container:
  port: 8000

env:
  SERVICE_NAME: release-api
  APP_VERSION: v0.1.0

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 3
    periodSeconds: 5
    failureThreshold: 3
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
