apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release-api.fullname" . }}-config
  labels:
    {{- include "release-api.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME | quote }}
  APP_VERSION: {{ .Values.env.APP_VERSION | quote }}
